services:
  geopol:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ["./start_sim.sh"]
    # command: "tail -f /dev/null"
    image: geopol:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    container_name: geopol
    hostname: geopol
    healthcheck:
      test: bash -c "[ -f /data/geopol/local/game.id ]"
      timeout: 3s
      retries: 20
    volumes:
      - '${PWD}/config/local:/home/geopol/.config/geopol'
      - '${PWD}/logs:/home/geopol/logs'
      - '${PWD}/data:/data/geopol'
    # ports:
    #   - 8080:8000

  geopol-ui:
    build:
      context: .
      dockerfile: Dockerfile
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    command: "geopol_server -c /home/geopol/.config/geopol/wotr_unmasked.yaml -l /home/geopol/logs/local/geopol-ui.log"
    image: geopol:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    container_name: geopol-ui
    hostname: geopol-ui
    volumes:
      - '${PWD}/config/local:/home/geopol/.config/geopol'
      - '${PWD}/logs:/home/geopol/logs'
      - '${PWD}/data:/data/geopol'
    ports:
      - 8080:8000
    depends_on:
      geopol:
        condition: service_healthy

#   geopol-openai:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               count: all
#               capabilities: [gpu]
#     command: ["./start_sim_openai.sh"]
#     image: geopol:latest
#     stdin_open: true # docker run -i
#     tty: true # docker run -t
#     container_name: geopol-openai
#     hostname: geopol-openai
#     healthcheck:
#       test: bash -c "[ -f /data/geopol/openai/game.id ]"
#       timeout: 3s
#       retries: 20
#     volumes:
#       - '${PWD}/config/openai:/home/geopol/.config/geopol'
#       - '${PWD}/logs:/home/geopol/logs'
#       - '${PWD}/data:/data/geopol'
#     secrets:
#       - openai_key
#     # ports:
#     #   - 8080:8000

#   geopol-ui-openai:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     # deploy:
#     #   resources:
#     #     reservations:
#     #       devices:
#     #         - driver: nvidia
#     #           count: all
#     #           capabilities: [gpu]
#     command: "geopol_server -c /home/geopol/.config/geopol/wotr_unmasked-openai.yaml -l /home/geopol/logs/openai/geopol-ui.log"
#     image: geopol:latest
#     stdin_open: true # docker run -i
#     tty: true # docker run -t
#     container_name: geopol-ui-openai
#     hostname: geopol-ui-openai
#     volumes:
#       - '${PWD}/config/openai:/home/geopol/.config/geopol'
#       - '${PWD}/logs:/home/geopol/logs'
#       - '${PWD}/data:/data/geopol'
#     ports:
#       - 8081:8000
#     depends_on:
#       geopol-openai:
#         condition: service_healthy
# secrets:
#   openai_key:
#     file: ${PWD}/secrets/openaiapi.key
