services:
  geopol:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: "geopol_game"
    image: geopol:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    container_name: geopol
    hostname: geopol
    healthcheck:
      test: bash -c "[ -f /data/geopol/game.id ]"
      timeout: 3s
      retries: 20
    volumes:
      - '${PWD}/config:/config'
      - '${PWD}/logs:/home/geopol/logs'
      - '${PWD}/data:/data/geopol'
    # ports:
    #   - 8080:8000

  geopol-ui:
    build:
      context: .
      dockerfile: Dockerfile
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    command: "geopol_server"
    image: geopol:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    container_name: geopol-ui
    hostname: geopol-ui
    volumes:
      - '${PWD}/config:/config'
      - '${PWD}/logs:/home/geopol/logs'
      - '${PWD}/data:/data/geopol'
    ports:
      - 8080:8000
    depends_on:
      geopol:
        condition: service_healthy
