#!/usr/bin/env python3

"""LLM-driven Typst report generation for Geopol Forecaster simulations.

Instead of string-concatenation templates, an LLM agent generates the Typst
markup with access to syntax rules and the project's style guide. Falls back
to the template-based report.py on any failure.
"""

import os
import subprocess
import datetime
import re
import time


# Typst syntax quick-reference (from typst-skills) + project style guide
TYPST_REPORT_SYSTEM_PROMPT = """\
You are a professional document formatter producing a Typst (.typ) report
for a geopolitical wargaming simulation. You must output ONLY valid Typst
markup — no markdown, no commentary, no code fences.

## Typst Syntax Rules (CRITICAL — your training data may be wrong)

- Arrays: `(item1, item2)` — parentheses, NOT square brackets.
- Dictionaries: `(key: value, key2: value2)`.
- Content blocks: `[markup content]` — square brackets.
- Use `#` to start code expressions inside markup. Do NOT use `#` inside
  code contexts (argument lists, code blocks).
- `set` rules configure defaults: `#set text(font: "IBM Plex Sans")`
- `show` rules transform elements: `#show heading.where(level: 1): it => ...`
- NO LaTeX syntax. No `\\begin`, `\\section`, etc.
- Access array elements with `.at(0)`, not `[0]`.
- Use `table()` not `tabular`.
- Strings use double quotes only.

## Project Style Guide

You MUST use these exact style settings:

```typst
#set document(title: "TITLE", author: "Geopol Forecaster")
#set text(font: "IBM Plex Sans", size: 10.5pt, fill: rgb("#1a1a1a"))
#set par(justify: true, leading: 0.65em)
#set heading(numbering: "1.")

#set page(
  paper: "a4",
  margin: (top: 2.5cm, bottom: 2.5cm, left: 2cm, right: 2cm),
  header: context {
    if counter(page).get().first() > 1 {
      set text(8pt, fill: rgb("#888888"))
      [Geopol Forecaster Report #h(1fr) TITLE]
      line(length: 100%, stroke: 0.4pt + rgb("#cccccc"))
    }
  },
  footer: {
    set text(8pt, fill: rgb("#888888"))
    line(length: 100%, stroke: 0.4pt + rgb("#cccccc"))
    v(4pt)
    [Generated by Geopol Forecaster #h(1fr) Page #context counter(page).display("1 of 1", both: true)]
  },
)
```

Heading styles:
- Level 1: 16pt, bold, rgb("#2c3e50"), underlined with 1pt rule
- Level 2: 13pt, bold, rgb("#34495e")
- Level 3: 11pt, bold, rgb("#546e7a")

Player/actor response blocks: light grey background rgb("#f8f9fa") with
left blue border (3pt, rgb("#3498db")), rounded corners.

Assessment blocks: light yellow background rgb("#fef9e7") with gold
border (0.5pt, rgb("#f0c040")).

Configuration tables: alternating first-column fill rgb("#f5f6fa"),
light grey stroke rgb("#dddddd").

## Document Structure

Produce a complete Typst document with:

1. **Title page** — large title, subtitle "Simulation Report", date,
   runtime info, model configuration table
2. **Table of contents**
3. **Executive Summary** — 3-5 sentence overview of the simulation outcome
4. **SITREP / Intelligence Briefing** — the pre-simulation intelligence
5. **Scenario** — the scenario as given
6. **Simulation Narrative** — each move/round with actor responses in
   styled blocks, adjudication narrative
7. **Assessments** — Q&A results in assessment-styled blocks
8. **Actor Profiles** — brief table or summary of each actor's role and model
9. **Run Configuration** — metadata table (title, moves, timestep, mode,
   runtime, date)

## Formatting Enhancements

You may add:
- Actor name labels/tags on response blocks
- Summary callout boxes
- Structured tables for force disposition if data is present
- A timeline sidebar or numbered progression for moves
- Bold key findings in assessments

## Rules

- Output ONLY the Typst document. No explanation, no markdown fences.
- Escape user/LLM-generated text that contains Typst special characters:
  #, *, _, @, $, <, >, ~, ` — prefix each with a backslash.
- The document must compile with `typst compile` without errors.
- Keep the professional intelligence-report tone.
"""


async def generate_report_agent(state, llm_client, model,
                                 output_dir=None, runtime_seconds=None):
    """Generate a Typst PDF report using an LLM agent.

    The agent receives the full simulation state and produces formatted
    Typst markup. If the agent output fails to compile, falls back to
    the template-based generator.

    Args:
        state: Completed simulation state dict.
        llm_client: LLMClient instance.
        model: Model ID for the report-writing agent.
        output_dir: Directory for output files.
        runtime_seconds: Total simulation runtime.

    Returns:
        Path to the generated PDF file.
    """
    if output_dir is None:
        output_dir = ".geopol_data/reports"
    os.makedirs(output_dir, exist_ok=True)

    ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    title_slug = _slugify(state.get("title", "simulation"))
    typ_path = os.path.join(output_dir, f"{title_slug}_{ts}.typ")
    pdf_path = typ_path.replace(".typ", ".pdf")

    # Build the user prompt with all simulation data
    user_content = _build_agent_prompt(state, runtime_seconds)

    messages = [
        {"role": "system", "content": TYPST_REPORT_SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]

    print("[report-agent] Generating Typst document via LLM...")

    try:
        typ_content = await llm_client.complete(
            model=model, messages=messages,
            max_tokens=12000, temperature=0.2,
        )

        # Strip any markdown code fences the LLM might have added
        typ_content = _strip_code_fences(typ_content)

        # Write and try to compile
        with open(typ_path, "w") as f:
            f.write(typ_content)

        result = subprocess.run(
            ["typst", "compile", typ_path, pdf_path],
            capture_output=True, text=True,
        )

        if result.returncode == 0:
            print(f"[report-agent] PDF generated: {pdf_path}")
            return pdf_path
        else:
            print(f"[report-agent] Typst compilation failed: {result.stderr[:500]}")
            print("[report-agent] Falling back to template-based report...")
            return _fallback_report(state, output_dir, runtime_seconds)

    except Exception as e:
        print(f"[report-agent] Agent failed: {e}")
        print("[report-agent] Falling back to template-based report...")
        return _fallback_report(state, output_dir, runtime_seconds)


def _build_agent_prompt(state, runtime_seconds=None):
    """Build the user prompt containing all simulation data."""
    title = state.get("title", "Simulation")
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M UTC")

    parts = []
    parts.append(f"## Report Metadata")
    parts.append(f"- Title: {title}")
    parts.append(f"- Generated: {now}")
    if runtime_seconds is not None:
        parts.append(f"- Runtime: {_format_runtime(runtime_seconds)}")
    parts.append(f"- Moves: {state.get('moves_total', '?')}")
    parts.append(f"- Timestep: {state.get('timestep', '?')}")
    parts.append(f"- Mode: {', '.join(state.get('mode', []))}")
    parts.append("")

    # Player/model config
    player_configs = state.get("player_configs", [])
    if player_configs:
        parts.append("## Actor / Model Configuration")
        for p in player_configs:
            parts.append(f"- {p.get('name', 'Player')}: model `{p.get('model_id', '?')}`")
            if p.get("persona"):
                # Truncate long personas
                persona = p["persona"][:300]
                parts.append(f"  Persona: {persona}")
        parts.append("")

    # Scenario
    parts.append("## Scenario Text")
    parts.append(state.get("scenario", "(no scenario)"))
    parts.append("")

    # Briefing / SITREP
    briefing = state.get("briefing", "")
    if briefing:
        parts.append("## SITREP / Intelligence Briefing")
        parts.append(briefing)
        parts.append("")

    # History / Narrative
    history = state.get("history", [])
    if history:
        parts.append("## Simulation History")
        for entry in history:
            name = entry.get("name", "")
            text = entry.get("text", "")
            move = entry.get("move", "")
            if name in ("Narrator", "Briefing"):
                continue
            move_label = f" (Move {move})" if move else ""
            parts.append(f"### {name}{move_label}")
            parts.append(text)
            parts.append("")

    # Assessments
    assessments = state.get("assessments", [])
    if assessments:
        parts.append("## Assessments")
        for i, a in enumerate(assessments, 1):
            parts.append(f"### Q{i}: {a.get('question', '')}")
            if a.get("options"):
                parts.append(f"Options: {', '.join(a['options'])}")
            parts.append(f"Answer: {a.get('answer', '')}")
            parts.append("")

    parts.append("## Task")
    parts.append("Produce the complete Typst document now. Output ONLY Typst markup.")

    return "\n".join(parts)


def _strip_code_fences(text):
    """Remove markdown code fences if the LLM wrapped the output."""
    text = text.strip()
    # Remove ```typst ... ``` wrapping
    if text.startswith("```"):
        lines = text.split("\n")
        # Remove first line (```typst or ```)
        lines = lines[1:]
        # Remove last line if it's ```
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines)
    return text


def _fallback_report(state, output_dir, runtime_seconds):
    """Fall back to the template-based report generator."""
    from .report import generate_report
    return generate_report(state, output_dir=output_dir,
                           runtime_seconds=runtime_seconds)


def _format_runtime(seconds):
    """Format runtime seconds into a human-readable string."""
    if seconds < 60:
        return f"{seconds:.1f}s"
    minutes = int(seconds // 60)
    secs = int(seconds % 60)
    if minutes < 60:
        return f"{minutes}m {secs}s"
    hours = int(minutes // 60)
    mins = minutes % 60
    return f"{hours}h {mins}m {secs}s"


def _slugify(text):
    """Convert text to a filesystem-safe slug."""
    text = text.lower().strip()
    text = re.sub(r"[^a-z0-9]+", "_", text)
    return text[:30].strip("_")
