#!/usr/bin/env python3

"""Typst PDF report generation for snowglobe simulations."""

import os
import subprocess
import datetime
import re
import time


def generate_report(state, output_dir=None, runtime_seconds=None):
    """Generate a Typst PDF report from the completed simulation state.

    Writes a .typ source file, compiles it with `typst compile`, and
    returns the path to the generated PDF.
    """
    if output_dir is None:
        output_dir = ".snowglobe_data/reports"

    os.makedirs(output_dir, exist_ok=True)

    ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    title_slug = _slugify(state.get("title", "simulation"))
    typ_path = os.path.join(output_dir, f"{title_slug}_{ts}.typ")
    pdf_path = typ_path.replace(".typ", ".pdf")

    typ_content = _build_typst_document(state, runtime_seconds=runtime_seconds)

    with open(typ_path, "w") as f:
        f.write(typ_content)

    subprocess.run(
        ["typst", "compile", typ_path, pdf_path],
        check=True,
        capture_output=True,
    )

    return pdf_path


def _build_typst_document(state, runtime_seconds=None):
    """Build the Typst markup string from simulation state."""
    title = state.get("title", "Simulation")
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    sections = []

    # --- Document setup ---
    sections.append(f'#set document(title: "{_esc(title)}", author: "Snowglobe")')
    sections.append('#set text(font: "IBM Plex Sans", size: 10.5pt, fill: rgb("#1a1a1a"))')
    sections.append("#set par(justify: true, leading: 0.65em)")
    sections.append('#set heading(numbering: "1.")')
    sections.append("")

    # Page layout with header, footer, page numbers
    sections.append("#set page(")
    sections.append('  paper: "a4",')
    sections.append("  margin: (top: 2.5cm, bottom: 2.5cm, left: 2cm, right: 2cm),")
    sections.append("  header: context {")
    sections.append("    if counter(page).get().first() > 1 {")
    sections.append("      set text(8pt, fill: rgb(\"#888888\"))")
    sections.append(f'      [Snowglobe Simulation Report #h(1fr) {_esc(title)}]')
    sections.append("      line(length: 100%, stroke: 0.4pt + rgb(\"#cccccc\"))")
    sections.append("    }")
    sections.append("  },")
    sections.append("  footer: {")
    sections.append("    set text(8pt, fill: rgb(\"#888888\"))")
    sections.append("    line(length: 100%, stroke: 0.4pt + rgb(\"#cccccc\"))")
    sections.append("    v(4pt)")
    sections.append('    [Generated by Snowglobe #h(1fr) Page #context counter(page).display("1 of 1", both: true)]')
    sections.append("  },")
    sections.append(")")
    sections.append("")

    # Heading styling
    sections.append("#show heading.where(level: 1): it => {")
    sections.append("  set text(16pt, weight: \"bold\", fill: rgb(\"#2c3e50\"))")
    sections.append("  v(0.8em)")
    sections.append("  it")
    sections.append("  v(0.4em)")
    sections.append("  line(length: 100%, stroke: 1pt + rgb(\"#2c3e50\"))")
    sections.append("  v(0.4em)")
    sections.append("}")
    sections.append("")
    sections.append("#show heading.where(level: 2): it => {")
    sections.append("  set text(13pt, weight: \"bold\", fill: rgb(\"#34495e\"))")
    sections.append("  v(0.6em)")
    sections.append("  it")
    sections.append("  v(0.3em)")
    sections.append("}")
    sections.append("")
    sections.append("#show heading.where(level: 3): it => {")
    sections.append("  set text(11pt, weight: \"bold\", fill: rgb(\"#546e7a\"))")
    sections.append("  v(0.4em)")
    sections.append("  it")
    sections.append("  v(0.2em)")
    sections.append("}")
    sections.append("")

    # --- Title page ---
    sections.append("#v(3cm)")
    sections.append("#align(center)[")
    sections.append(f"  #text(28pt, weight: \"bold\", fill: rgb(\"#2c3e50\"))[{_esc(title)}]")
    sections.append("")
    sections.append("  #v(0.5cm)")
    sections.append(f'  #text(12pt, fill: rgb("#7f8c8d"))[Simulation Report]')
    sections.append("")
    sections.append("  #v(1cm)")
    sections.append('  #line(length: 40%, stroke: 1.5pt + rgb("#2c3e50"))')
    sections.append("  #v(1cm)")
    sections.append("")
    sections.append(f'  #text(11pt, fill: rgb("#555555"))[Generated {now}]')
    sections.append("")

    # Runtime info on title page
    if runtime_seconds is not None:
        rt = _format_runtime(runtime_seconds)
        sections.append(f'  #text(11pt, fill: rgb("#555555"))[Runtime: {rt}]')
        sections.append("")

    sections.append(f'  #text(10pt, fill: rgb("#888888"))[Snowglobe LLM Wargaming Framework]')
    sections.append("]")
    sections.append("")

    # Model pool info on title page
    player_configs = state.get("player_configs", [])
    if player_configs:
        sections.append("#v(2cm)")
        sections.append("#align(center)[")
        sections.append('#text(10pt, fill: rgb("#7f8c8d"))[Model Configuration]')
        sections.append("")
        sections.append("#v(0.3cm)")
        sections.append("#table(")
        sections.append("  columns: (auto, auto),")
        sections.append('  stroke: 0.5pt + rgb("#dddddd"),')
        sections.append("  inset: 8pt,")
        sections.append('  fill: (col, _) => if col == 0 { rgb("#f5f6fa") },')
        for p in player_configs:
            sections.append(f'  [*{_esc(p.get("name", "Player"))}*], [{_esc(p.get("model_id", "?"))}],')
        sections.append(")")
        sections.append("]")
    sections.append("")
    sections.append("#pagebreak()")
    sections.append("")

    # --- Table of contents ---
    sections.append('#heading(outlined: false, numbering: none)[Contents]')
    sections.append("#v(0.8em)")
    sections.append("#outline(title: none, indent: 1.5em, depth: 3)")
    sections.append("#pagebreak()")
    sections.append("")

    # --- Scenario ---
    sections.append("= Scenario")
    sections.append("")
    sections.append(_esc(state.get("scenario", "")))
    sections.append("")

    # --- Briefing ---
    briefing = state.get("briefing", "")
    if briefing:
        sections.append("= Intelligence Briefing")
        sections.append("")
        sections.append(_esc(briefing))
        sections.append("")

    # --- Simulation Narrative ---
    sections.append("= Simulation Narrative")
    sections.append("")

    history = state.get("history", [])
    current_move = 0
    for entry in history:
        name = entry.get("name", "")
        text = entry.get("text", "")
        move = entry.get("move", None)

        if name in ("Narrator", "Briefing"):
            continue

        # Insert move divider when move number changes
        if move is not None and move != current_move:
            current_move = move
            timestep = state.get("timestep", "turn")
            sections.append(f"== Move {current_move} ({_esc(timestep.capitalize())} {current_move})")
            sections.append("")

        sections.append(f"=== {_esc(name)}")
        sections.append("")

        # Wrap player responses in a subtle block
        sections.append("#block(")
        sections.append('  fill: rgb("#f8f9fa"),')
        sections.append('  stroke: (left: 3pt + rgb("#3498db")),')
        sections.append("  inset: (left: 12pt, top: 8pt, bottom: 8pt, right: 8pt),")
        sections.append("  radius: 2pt,")
        sections.append("  width: 100%,")
        sections.append(f"  [{_esc(text)}]")
        sections.append(")")
        sections.append("")

    # --- Assessments ---
    assessments = state.get("assessments", [])
    if assessments:
        sections.append("= Assessments")
        sections.append("")
        for i, a in enumerate(assessments, 1):
            question = a.get("question", "")
            answer = a.get("answer", "")
            options = a.get("options")

            sections.append("#block(")
            sections.append('  fill: rgb("#fef9e7"),')
            sections.append('  stroke: 0.5pt + rgb("#f0c040"),')
            sections.append("  inset: 10pt,")
            sections.append("  radius: 3pt,")
            sections.append("  width: 100%,")
            sections.append("  [")
            sections.append(f"    *Q{i}: {_esc(question)}*")
            sections.append("")
            if options:
                sections.append(
                    f"    _Options: {', '.join(_esc(o) for o in options)}_"
                )
                sections.append("")
            sections.append(f"    *A: {_esc(answer)}*")
            sections.append("  ]")
            sections.append(")")
            sections.append("")

    # --- Configuration / Run Metadata ---
    sections.append("= Run Configuration")
    sections.append("")

    config_items = [
        ("Simulation Title", title),
        ("Moves", str(state.get("moves_total", "?"))),
        ("Timestep", state.get("timestep", "?")),
        ("Mode", ", ".join(state.get("mode", []))),
        ("Generated", now),
    ]
    if runtime_seconds is not None:
        config_items.append(("Runtime", _format_runtime(runtime_seconds)))

    sections.append("#table(")
    sections.append("  columns: (1fr, 2fr),")
    sections.append('  stroke: 0.5pt + rgb("#dddddd"),')
    sections.append("  inset: 8pt,")
    sections.append('  fill: (col, _) => if col == 0 { rgb("#f5f6fa") },')
    for key, val in config_items:
        sections.append(f"  [*{_esc(key)}*], [{_esc(val)}],")
    sections.append(")")
    sections.append("")

    # Player/model table
    if player_configs:
        sections.append('#heading(numbering: none, level: 3)[Model Assignments]')
        sections.append("")
        sections.append("#table(")
        sections.append("  columns: (1fr, 2fr),")
        sections.append('  stroke: 0.5pt + rgb("#dddddd"),')
        sections.append("  inset: 8pt,")
        sections.append('  fill: (col, _) => if col == 0 { rgb("#f5f6fa") },')
        for p in player_configs:
            sections.append(f'  [*{_esc(p.get("name", "Player"))}*], [`{_esc(p.get("model_id", "?"))}`],')
        sections.append(")")
        sections.append("")

    return "\n".join(sections)


def _format_runtime(seconds):
    """Format runtime seconds into a human-readable string."""
    if seconds < 60:
        return f"{seconds:.1f}s"
    minutes = int(seconds // 60)
    secs = int(seconds % 60)
    if minutes < 60:
        return f"{minutes}m {secs}s"
    hours = int(minutes // 60)
    mins = minutes % 60
    return f"{hours}h {mins}m {secs}s"


def _esc(text):
    """Escape Typst special characters in user/LLM-generated text."""
    if not isinstance(text, str):
        text = str(text)
    # Order matters: backslash first to avoid double-escaping
    for char in ["\\", "#", "*", "_", "@", "$", "<", ">", "~", "`"]:
        text = text.replace(char, "\\" + char)
    return text


def _slugify(text):
    """Convert text to a filesystem-safe slug."""
    text = text.lower().strip()
    text = re.sub(r"[^a-z0-9]+", "_", text)
    return text[:30].strip("_")
